name: .NET Build and Test

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures the full repo is checked out

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # Matches your project

      - name: Verify directory structure (for debugging)
        run: |
          Write-Output "Current Directory: $(Get-Location)"
          Get-ChildItem -Recurse

      - name: Restore dependencies
        run: dotnet restore PopulationReportingSystem.sln

      - name: Build the project
        run: dotnet build PopulationReportingSystem.sln --configuration Release

      - name: Run tests (if available)
        run: dotnet test PopulationReportingSystem.sln --no-build --verbosity normal
